# Generated by Django 4.1.2 on 2022-11-19 15:16

from django.db import migrations, models
import martor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("specialists", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Clinic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=255)),
                ("description", martor.models.MartorField(blank=True)),
                ("avatar", models.ImageField(blank=True, upload_to="avatars_clinic/")),
                (
                    "Cover_photo",
                    models.ImageField(blank=True, upload_to="cover_photos_clinic/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "specialists",
                    models.ManyToManyField(
                        related_name="specialist_clinics", to="specialists.specialist"
                    ),
                ),
            ],
            options={
                "db_table": "clinics",
            },
        ),
    ]
