# Generated by Django 4.1.2 on 2022-11-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clinic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=255)),
                ("description_html", models.TextField(blank=True)),
                ("description_markdown", models.TextField(blank=True)),
                ("avatar", models.ImageField(blank=True, upload_to="avatars_clinic/")),
                (
                    "Cover_photo",
                    models.ImageField(blank=True, upload_to="cover_photos_clinic/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "clinics",
            },
        ),
    ]
