# Generated by Django 4.1.2 on 2022-11-13 05:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clinics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Specialist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description_html", models.TextField(blank=True)),
                ("description_markdown", models.TextField(blank=True)),
                (
                    "avatar",
                    models.ImageField(blank=True, upload_to="avatars_specialist/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clinics",
                    models.ManyToManyField(
                        related_name="clinic_specialists", to="clinics.clinic"
                    ),
                ),
                (
                    "doctors",
                    models.ManyToManyField(
                        related_name="doctor_specialists", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "specialists",
            },
        ),
    ]
